apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.service.type: NodePort
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: mosquitto
  name: mosquitto
spec:
  ports:
  - name: "1983"
    port: 1983
    targetPort: 1883
  selector:
    io.kompose.service: mosquitto
  type: NodePort
status:
  loadBalancer: {}
