apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.service.type: NodePort
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: wildfly
  name: wildfly
spec:
  ports:
  - name: "9091"
    port: 9091
    targetPort: 9091
  - name: "9090"
    port: 9090
    targetPort: 9090
  - name: "5884"
    port: 5884
    targetPort: 5784
  selector:
    io.kompose.service: wildfly
  type: NodePort
status:
  loadBalancer: {}
